name: deploy
on:
  push:
    branches:
      - main
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: CDK Deploy
        run: |
          npm install
          npm run build
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          LINGDOCS_DICTIONARY_SPREADSHEET: ${{ secrets.LINGDOCS_DICTIONARY_SPREADSHEET }}
          LINGDOCS_DICTIONARY_SHEET_ID: ${{ secrets.LINGDOCS_DICTIONARY_SHEET_ID }}
          LINGDOCS_SERVICE_ACCOUNT_EMAIL: ${{ secrets.LINGDOCS_SERVICE_ACCOUNT_EMAIL }}
          LINGDOCS_SERVICE_ACCOUNT_KEY: ${{ secrets.LINGDOCS_SERVICE_ACCOUNT_KEY }}
          DICT_R2_ENDPOINT: ${{ secrets.DICT_R2_ENDPOINT }}
          DICT_R2_KEY_ID: ${{ secrets.DICT_R2_KEY_ID }}
          DICT_R2_KEY_SECRET: ${{ secrets.DICT_R2_KEY_SECRET }}
          DICT_R2_BUCKET: ${{ secrets.DICT_R2_BUCKET }}

